# Generated by Django 3.2.25 on 2024-03-27 07:47

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
